import os

SQLALCHEMY_DATABASE_URI = os.getenv('CLEARDB_DATABASE_URL')
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_POOL_RECYCLE = 30

SESSION_TYPE = 'filesystem'

KEY = os.getenv('KEY')
SECRET_KEY = os.getenv('SECRET_KEY')
